groups:
- name: alert.rules
  rules:
  - alert: InstanceDown
    expr: up == 0
    for: 5s
    labels:
      severity: critical
    annotations:
      description: '{{ $labels.instance }} of job {{ $labels.job }} has been down
        for more than 5 secs.'
      summary: Instance {{ $labels.instance }} down
- name: host
  rules:
  - alert: high_cpu_load
    expr: node_load1 > 1
    for: 5s
    labels:
      severity: critical
    annotations:
      summary: Instance {{ $labels.instance }} host cpu is high PIDOR!!
      description: '{{ $labels.instance }} of job {{ $labels.job }} has been HIGH CPU SUKA
        for more than 5 secs.'

